export const SORT_OPTIONS = [
  { id: "none", title: "None (Default)" },
  { id: "relevance", title: "Relevance" },
  { id: "lastUploadedChapterAt", title: "Latest Updates" },
  { id: "createdAt", title: "Recently Added" },
  { id: "rating", title: "Highest Rated" },
  { id: "views", title: "Most Popular" },
  { id: "follows", title: "Most Followed" },
  { id: "title", title: "Title (A-Z)" },
  { id: "year", title: "Year" },
];

export const SUBTITLE_OPTIONS = [
  { id: "status", title: "Status (Default)" },
  { id: "year", title: "Year" },
  { id: "content_rating", title: "Content Rating" },
];

export const ITEMS_PER_PAGE_OPTIONS = [
  { id: "28", title: "28" },
  { id: "42", title: "42 (Default)" },
  { id: "56", title: "56" },
  { id: "70", title: "70" },
  { id: "84", title: "84" },
  { id: "98", title: "98" },
];

export const AVAILABLE_LANGUAGES = [
  { id: "en", title: "English" },
  { id: "ja", title: "Japanese" },
  { id: "ko", title: "Korean" },
  { id: "zh", title: "Chinese (Simplified)" },
  { id: "zh-hk", title: "Chinese (Traditional)" },
  { id: "id", title: "Indonesian" },
  { id: "jv", title: "Javanese" },
  { id: "vi", title: "Vietnamese" },
  { id: "af", title: "Afrikaans" },
  { id: "sq", title: "Albanian" },
  { id: "ar", title: "Arabic" },
  { id: "az", title: "Azerbaijani" },
  { id: "eu", title: "Basque" },
  { id: "be", title: "Belarusian" },
  { id: "bn", title: "Bengali" },
  { id: "bg", title: "Bulgarian" },
  { id: "my", title: "Burmese" },
  { id: "ca", title: "Catalan" },
  { id: "cv", title: "Chuvash" },
  { id: "hr", title: "Croatian" },
  { id: "cs", title: "Czech" },
  { id: "da", title: "Danish" },
  { id: "nl", title: "Dutch" },
  { id: "eo", title: "Esperanto" },
  { id: "et", title: "Estonian" },
  { id: "tl", title: "Filipino" },
  { id: "fi", title: "Finnish" },
  { id: "fr", title: "French" },
  { id: "ka", title: "Georgian" },
  { id: "de", title: "German" },
  { id: "el", title: "Greek" },
  { id: "he", title: "Hebrew" },
  { id: "hi", title: "Hindi" },
  { id: "hu", title: "Hungarian" },
  { id: "ga", title: "Irish" },
  { id: "it", title: "Italian" },
  { id: "kk", title: "Kazakh" },
  { id: "la", title: "Latin" },
  { id: "lt", title: "Lithuanian" },
  { id: "ms", title: "Malay" },
  { id: "mn", title: "Mongolian" },
  { id: "ne", title: "Nepali" },
  { id: "no", title: "Norwegian" },
  { id: "fa", title: "Persian" },
  { id: "pl", title: "Polish" },
  { id: "pt", title: "Portuguese" },
  { id: "pt-br", title: "Portuguese (Brazil)" },
  { id: "ro", title: "Romanian" },
  { id: "ru", title: "Russian" },
  { id: "sr", title: "Serbian" },
  { id: "sk", title: "Slovak" },
  { id: "sl", title: "Slovenian" },
  { id: "es", title: "Spanish" },
  { id: "es-la", title: "Spanish (LATAM)" },
  { id: "sv", title: "Swedish" },
  { id: "tam", title: "Tamil" },
  { id: "te", title: "Telugu" },
  { id: "th", title: "Thai" },
  { id: "tr", title: "Turkish" },
  { id: "uk", title: "Ukrainian" },
  { id: "ur", title: "Urdu" },
  { id: "uz", title: "Uzbek" },
];
