export const genres = [
    { id: "artbook", value: "Artbook" },
    { id: "cartoon", value: "Cartoon" },
    { id: "comic", value: "Comic" },
    { id: "doujinshi", value: "Doujinshi" },
    { id: "imageset", value: "Imageset" },
    { id: "manga", value: "Manga" },
    { id: "manhua", value: "Manhua" },
    { id: "manhwa", value: "Manhwa" },
    { id: "webtoon", value: "Webtoon" },
    { id: "western", value: "Western" },
    { id: "_4_koma", value: "4-Koma" },
    { id: "oneshot", value: "Oneshot" },
    { id: "shoujo", value: "Shoujo(G)" },
    { id: "shounen", value: "Shounen(B)" },
    { id: "josei", value: "Josei(W)" },
    { id: "seinen", value: "Seinen(M)" },
    { id: "yuri", value: "Yuri(GL)" },
    { id: "yaoi", value: "Yaoi(BL)" },
    { id: "bara", value: "Bara(ML)" },
    { id: "kodomo", value: "Kodomo(Kid)" },
    { id: "old_people", value: "Silver & Golden" },
    { id: "non_human", value: "Non-human" },
    { id: "gore", value: "Gore" },
    { id: "bloody", value: "Bloody" },
    { id: "violence", value: "Violence" },
    { id: "ecchi", value: "Ecchi" },
    { id: "adult", value: "Adult" },
    { id: "mature", value: "Mature" },
    { id: "smut", value: "Smut" },
    { id: "hentai", value: "Hentai" },
    { id: "action", value: "Action" },
    { id: "adaptation", value: "Adaptation" },
    { id: "adventure", value: "Adventure" },
    { id: "age_gap", value: "Age Gap" },
    { id: "aliens", value: "Aliens" },
    { id: "animals", value: "Animals" },
    { id: "anthology", value: "Anthology" },
    { id: "beasts", value: "Beasts" },
    { id: "bodyswap", value: "Bodyswap" },
    { id: "boys", value: "Boys" },
    { id: "cars", value: "Cars" },
    { id: "cheating_infidelity", value: "Cheating/Infidelity" },
    { id: "childhood_friends", value: "Childhood Friends" },
    { id: "college_life", value: "College life" },
    { id: "comedy", value: "Comedy" },
    { id: "contest_winning", value: "Contest winning" },
    { id: "cooking", value: "Cooking" },
    { id: "crime", value: "Crime" },
    { id: "crossdressing", value: "Crossdressing" },
    { id: "dementia", value: "Dementia" },
    { id: "delinquents", value: "Delinquents" },
    { id: "demons", value: "Demons" },
    { id: "drama", value: "Drama" },
    { id: "dungeons", value: "Dungeons" },
    { id: "emperor_daughte", value: "Emperor's daughter" },
    { id: "fan_colored", value: "Fan-Colored" },
    { id: "fantasy", value: "Fantasy" },
    { id: "fetish", value: "Fetish" },
    { id: "full_color", value: "Full Color" },
    { id: "game", value: "Game" },
    { id: "gender_bender", value: "Gender Bender" },
    { id: "genderswap", value: "Genderswap" },
    { id: "ghosts", value: "Ghosts" },
    { id: "girls", value: "Girls" },
    { id: "gyaru", value: "Gyaru" },
    { id: "harlequin", value: "Harlequin" },
    { id: "harem", value: "Harem" },
    { id: "historical", value: "Historical" },
    { id: "horror", value: "Horror" },
    { id: "incest", value: "Incest" },
    { id: "isekai", value: "Isekai" },
    { id: "kids", value: "Kids" },
    { id: "magical_girls", value: "Magical Girls" },
    { id: "magic", value: "Magic" },
    { id: "martial_arts", value: "Martial Arts" },
    { id: "mecha", value: "Mecha" },
    { id: "medical", value: "Medical" },
    { id: "military", value: "Military" },
    { id: "monster_girls", value: "Monster Girls" },
    { id: "monsters", value: "Monsters" },
    { id: "music", value: "Music" },
    { id: "mystery", value: "Mystery" },
    { id: "netorare", value: "Netorare/NTR" },
    { id: "ninja", value: "Ninja" },
    { id: "office_workers", value: "Office Workers" },
    { id: "omegaverse", value: "Omegaverse" },
    { id: "parody", value: "Parody" },
    { id: "philosophical", value: "Philosophical" },
    { id: "police", value: "Police" },
    { id: "post_apocalyptic", value: "Post-Apocalyptic" },
    { id: "psychological", value: "Psychological" },
    { id: "regression", value: "Regression" },
    { id: "reincarnation", value: "Reincarnation" },
    { id: "revenge", value: "Revenge" },
    { id: "reverse_harem", value: "Reverse Harem" },
    { id: "reverse_isekai", value: "Reverse Isekai" },
    { id: "romance", value: "Romance" },
    { id: "royal_family", value: "Royal family" },
    { id: "royalty", value: "Royalty" },
    { id: "samurai", value: "Samurai" },
    { id: "school_life", value: "School Life" },
    { id: "sci_fi", value: "Sci-Fi" },
    { id: "shoujo_ai", value: "Shoujo ai" },
    { id: "shounen_ai", value: "Shounen ai" },
    { id: "showbiz", value: "Showbiz" },
    { id: "slice_of_life", value: "Slice of Life" },
    { id: "sm_bdsm", value: "SM/BDSM/SUB-DOM" },
    { id: "space", value: "Space" },
    { id: "sports", value: "Sports" },
    { id: "super_power", value: "Super Power" },
    { id: "superhero", value: "Superhero" },
    { id: "supernatural", value: "Supernatural" },
    { id: "survival", value: "Survival" },
    { id: "thriller", value: "Thriller" },
    { id: "time_travel", value: "Time Travel" },
    { id: "tower_climbing", value: "Tower Climbing" },
    { id: "traditional_games", value: "Traditional Games" },
    { id: "tragedy", value: "Tragedy" },
    { id: "transmigration", value: "Transmigration" },
    { id: "vampires", value: "Vampires" },
    { id: "video_games", value: "Video Games" },
    { id: "villainess", value: "Villainess" },
    { id: "virtual_reality", value: "Virtual Reality" },
    { id: "wuxia", value: "Wuxia" },
    { id: "xianxia", value: "Xianxia" },
    { id: "xuanhuan", value: "Xuanhuan" },
    { id: "yakuzas", value: "Yakuzas" },
    { id: "zombies", value: "Zombies" },
];

export const matureGenres = [
    "Adult",
    "Ecchi",
    "Erotica",
    "Sexual violence",
    "Gore",
    "Bloody",
    "Violence",
    "Smut",
    "Hentai",
    "Yuri(GL)",
    "Yaoi(BL)",
    "Bara(ML)",
    "Netorare/NTR",
    "Incest",
    "SM/BDSM/SUB-DOM",
];

export const adultGenres = ["Erotica", "Sexual violence", "Hentai", "Smut"];
