export const languages = [
    { name: "اَلْعَرَبِيَّةُ", langCode: "ar" },
    { name: "български", langCode: "bg" },
    { name: "বাংলা", langCode: "bn" },
    { name: "Català", langCode: "ca" },
    { name: "Čeština", langCode: "cs" },
    { name: "Dansk", langCode: "da" },
    { name: "Deutsch", langCode: "de" },
    { name: "English", langCode: "en" },
    { name: "Español", langCode: "es" },
    { name: "Español (Latinoamérica)", langCode: "es-la" },
    { name: "فارسی", langCode: "fa" },
    { name: "Suomi", langCode: "fi" },
    { name: "Français", langCode: "fr" },
    { name: "עִבְרִית", langCode: "he" },
    { name: "हिन्दी", langCode: "hi" },
    { name: "Magyar", langCode: "hu" },
    { name: "Indonesia", langCode: "id" },
    { name: "Italiano", langCode: "it" },
    { name: "日本語", langCode: "ja" },
    { name: "한국어", langCode: "ko" },
    { name: "Lietuvių", langCode: "lt" },
    { name: "монгол", langCode: "mn" },
    { name: "Melayu", langCode: "ms" },
    { name: "မြန်မာဘာသာ", langCode: "my" },
    { name: "Nederlands", langCode: "nl" },
    { name: "Norsk", langCode: "no" },
    { name: "Polski", langCode: "pl" },
    { name: "Português", langCode: "pt" },
    { name: "Português (Brasil)", langCode: "pt-br" },
    { name: "Română", langCode: "ro" },
    { name: "Pусский", langCode: "ru" },
    { name: "Cрпски", langCode: "sr" },
    { name: "Svenska", langCode: "sv" },
    { name: "ไทย", langCode: "th" },
    { name: "Filipino", langCode: "tl" },
    { name: "Türkçe", langCode: "tr" },
    { name: "Yкраї́нська", langCode: "uk" },
    { name: "Tiếng Việt", langCode: "vi" },
    { name: "中文 (简化字)", langCode: "zh" },
    { name: "中文 (繁體字)", langCode: "zh-hk" },
    { name: "Afrikaans", langCode: "af" },
    { name: "Albanian", langCode: "sq" },
    { name: "Amharic", langCode: "am" },
    { name: "Armenian", langCode: "hy" },
    { name: "Azerbaijani", langCode: "az" },
    { name: "Belarusian", langCode: "be" },
    { name: "Bosnian", langCode: "bs" },
    { name: "Burmese", langCode: "my" },
    { name: "Cambodian", langCode: "km" },
    { name: "Cebuano", langCode: "ceb" },
    { name: "Chinese (繁)", langCode: "zh-hant" },
    { name: "Chinese (粵)", langCode: "yue" },
    { name: "Croatian", langCode: "hr" },
    { name: "Estonian", langCode: "et" },
    { name: "Faroese", langCode: "fo" },
    { name: "Georgian", langCode: "ka" },
    { name: "Greek", langCode: "el" },
    { name: "Guarani", langCode: "gn" },
    { name: "Gujarati", langCode: "gu" },
    { name: "Haitian Creole", langCode: "ht" },
    { name: "Hausa", langCode: "ha" },
    { name: "Icelandic", langCode: "is" },
    { name: "Igbo", langCode: "ig" },
    { name: "Irish", langCode: "ga" },
    { name: "Javanese", langCode: "jv" },
    { name: "Kannada", langCode: "kn" },
    { name: "Kazakh", langCode: "kk" },
    { name: "Kurdish", langCode: "ku" },
    { name: "Kyrgyz", langCode: "ky" },
    { name: "Laothian", langCode: "lo" },
    { name: "Latvian", langCode: "lv" },
    { name: "Luxembourgish", langCode: "lb" },
    { name: "Macedonian", langCode: "mk" },
    { name: "Malagasy", langCode: "mg" },
    { name: "Malayalam", langCode: "ml" },
    { name: "Maltese", langCode: "mt" },
    { name: "Maori", langCode: "mi" },
    { name: "Marathi", langCode: "mr" },
    { name: "Moldavian", langCode: "mo" },
    { name: "Nepali", langCode: "ne" },
    { name: "Nyanja", langCode: "ny" },
    { name: "Pashto", langCode: "ps" },
    { name: "Persian", langCode: "fa" },
    { name: "Portuguese (BR)", langCode: "pt-br" },
    { name: "Romansh", langCode: "rm" },
    { name: "Samoan", langCode: "sm" },
    { name: "Serbo-Croatian", langCode: "sh" },
    { name: "Sesotho", langCode: "st" },
    { name: "Shona", langCode: "sn" },
    { name: "Sindhi", langCode: "sd" },
    { name: "Sinhalese", langCode: "si" },
    { name: "Slovak", langCode: "sk" },
    { name: "Slovenian", langCode: "sl" },
    { name: "Somali", langCode: "so" },
    { name: "Spanish (LA)", langCode: "es-la" },
    { name: "Swahili", langCode: "sw" },
    { name: "Tajik", langCode: "tg" },
    { name: "Tamil", langCode: "ta" },
    { name: "Telugu", langCode: "te" },
    { name: "Tigrinya", langCode: "ti" },
    { name: "Tonga", langCode: "to" },
    { name: "Turkmen", langCode: "tk" },
    { name: "Urdu", langCode: "ur" },
    { name: "Uzbek", langCode: "uz" },
    { name: "Yoruba", langCode: "yo" },
    { name: "Zulu", langCode: "zu" },
    { name: "Other", langCode: "other" },
];
