/* SPDX-License-Identifier: GPL-3.0-or-later */
/* Copyright © 2026 Inkdex */

// Comix image-tile descrambler.
//
// Images may be served clean or with the tiles shuffled.
// A shuffled response is identified by these headers:
//
//   X-Scramble-Seed:  <uint32, decimal>   e.g. "3121655837"
//   X-Scramble-Grid:  <cols>x<rows>       e.g. "5x5"
//   X-Scramble-Algo:  <int>               permutation variant (default 2)
//   X-Scramble-Hash:  <token>             keys the seed: PRNG uses seed ^ XOR(token)
//
// The shuffle is row-major over a `cols * rows` tile grid, generated by a
// Fisher-Yates backward pass whose PRNG depends on the algo:
//   - algo <= 2: Numerical Recipes "ranqd1" LCG (any grid)
//   - algo 3:    xorshift32 seeded `seed | 1` (5x5 only)
//
//   for i from N-1 down to 1:
//     state = step(state)
//     j = state mod (i + 1)
//     swap arr[i], arr[j]
//
// `arr` starts as [0..N-1] and ends as the forward scramble permutation P,
// where scrambled_tile[i] = clean_tile[P[i]]. To descramble we want the
// inverse: clean[i] = scrambled[invP[i]].
//
// Tile size uses floor(W/cols) × floor(H/rows); the right/bottom remainder
// (when W or H isn't divisible by the grid) is left untouched by the
// server and passes through unchanged.

export interface ScrambleParams {
  seed: number;
  cols: number;
  rows: number;
  algo: number;
  seedHashXor: number;
}

function decodeScrambleHash(hash: string | undefined): number {
  switch (hash?.trim()) {
    case "03632":
      return 58414;
    case "02900":
      return 117532;
    default:
      return 0;
  }
}

function computeScramblePerm(seed: number, tileCount: number): number[] {
  let state = seed >>> 0;
  const arr: number[] = Array.from({ length: tileCount });
  for (let i = 0; i < tileCount; i++) arr[i] = i;
  for (let i = tileCount - 1; i > 0; i--) {
    state = (Math.imul(state, 1664525) + 1013904223) >>> 0;
    const j = state % (i + 1);
    const tmp = arr[i]!;
    arr[i] = arr[j]!;
    arr[j] = tmp;
  }
  return arr;
}

function computeDescrambleLookup(seed: number, tileCount: number): number[] {
  const P = computeScramblePerm(seed, tileCount);
  const inv: number[] = Array.from({ length: tileCount });
  for (let i = 0; i < tileCount; i++) inv[P[i]!] = i;
  return inv;
}

// Algo 3 (5x5 only): backward Fisher-Yates over an xorshift32 PRNG seeded `seed | 1`.
const ALGO3_TILES = 25;

function computeDescrambleLookupAlgo3(seed: number): number[] {
  const a: number[] = Array.from({ length: ALGO3_TILES });
  for (let i = 0; i < ALGO3_TILES; i++) a[i] = i;
  let s = (seed | 1) >>> 0;
  for (let i = ALGO3_TILES - 1; i > 0; i--) {
    s ^= s << 13;
    s >>>= 0;
    s ^= s >>> 17;
    s ^= s << 5;
    s >>>= 0;
    const j = s % (i + 1);
    const t = a[i]!;
    a[i] = a[j]!;
    a[j] = t;
  }
  const inv: number[] = Array.from({ length: ALGO3_TILES });
  for (let i = 0; i < ALGO3_TILES; i++) inv[a[i]!] = i;
  return inv;
}

function parseScrambleGrid(grid: string): { cols: number; rows: number } | null {
  const m = /^\s*(\d+)\s*x\s*(\d+)\s*$/i.exec(grid);
  if (!m) return null;
  const cols = parseInt(m[1]!, 10);
  const rows = parseInt(m[2]!, 10);
  if (!Number.isFinite(cols) || !Number.isFinite(rows) || cols <= 0 || rows <= 0) return null;
  return { cols, rows };
}

export function readScrambleHeaders(headers: Record<string, string>): ScrambleParams | null {
  let seedStr: string | undefined;
  let gridStr: string | undefined;
  let algoStr: string | undefined;
  let hashStr: string | undefined;
  for (const [key, value] of Object.entries(headers)) {
    const lk = key.toLowerCase();
    if (lk === "x-scramble-seed") seedStr = value;
    else if (lk === "x-scramble-grid") gridStr = value;
    else if (lk === "x-scramble-algo") algoStr = value;
    else if (lk === "x-scramble-hash") hashStr = value;
  }
  if (!seedStr || !gridStr) return null;
  const seed = parseInt(seedStr, 10);
  if (!Number.isFinite(seed) || seed < 0) return null;
  const grid = parseScrambleGrid(gridStr);
  if (!grid) return null;
  const algo = parseInt(algoStr ?? "", 10);
  return {
    seed,
    cols: grid.cols,
    rows: grid.rows,
    algo: Number.isFinite(algo) ? algo : 2,
    seedHashXor: decodeScrambleHash(hashStr),
  };
}

// Paperback's polyfill exposes HTMLCanvasElement and Image as direct
// constructors but omits Blob / URL / OffscreenCanvas, so image bytes
// cross the polyfill boundary via data: URLs.
async function loadImageFromBuffer(data: ArrayBuffer, mimeType: string): Promise<HTMLImageElement> {
  const b64 = Application.base64Encode(data);
  const b64Str = typeof b64 === "string" ? b64 : Application.arrayBufferToASCIIString(b64);
  const dataUrl = `data:${mimeType};base64,${b64Str}`;

  const img = new Image();
  return await new Promise<HTMLImageElement>((resolve, reject) => {
    if (img.complete && img.naturalWidth > 0) {
      resolve(img);
      return;
    }
    img.onload = () => resolve(img);
    img.onerror = (event) => {
      const msg = typeof event === "string" ? event : "image load failed";
      reject(new Error(msg));
    };
    img.src = dataUrl;
    if (img.complete && img.naturalWidth > 0) resolve(img);
  });
}

function decodeDataUrlToArrayBuffer(dataUrl: string): ArrayBuffer {
  const comma = dataUrl.indexOf(",");
  if (comma < 0) throw new Error("toDataURL returned malformed data URL");
  const payload = dataUrl.slice(comma + 1);
  const decoded = Application.base64Decode(payload);
  if (typeof decoded === "string") {
    const buf = new Uint8Array(decoded.length);
    for (let i = 0; i < decoded.length; i++) buf[i] = decoded.charCodeAt(i);
    return buf.buffer;
  }
  return decoded;
}

export async function descrambleImage(
  data: ArrayBuffer,
  params: ScrambleParams,
  mimeType: string,
): Promise<ArrayBuffer> {
  const { cols, rows, seed, algo, seedHashXor } = params;
  const effSeed = (seed ^ seedHashXor) >>> 0;
  const src = await loadImageFromBuffer(data, mimeType);
  const width = src.naturalWidth || src.width;
  const height = src.naturalHeight || src.height;

  const tw = (width / cols) | 0;
  const th = (height / rows) | 0;
  if (tw === 0 || th === 0) {
    throw new Error(`image ${width}x${height} too small for grid ${cols}x${rows}`);
  }
  let lookup: number[];
  if (algo === 3) {
    if (cols !== 5 || rows !== 5) {
      throw new Error(`algo 3 only supports a 5x5 grid, got ${cols}x${rows}`);
    }
    lookup = computeDescrambleLookupAlgo3(effSeed);
  } else {
    lookup = computeDescrambleLookup(effSeed, cols * rows);
  }

  const canvas = new HTMLCanvasElement();
  canvas.width = width;
  canvas.height = height;
  const ctx = canvas.getContext("2d");
  if (!ctx) throw new Error("failed to acquire 2d context");
  ctx.drawImage(src, 0, 0, width, height);

  // Paperback's polyfill exposes getImageData/putImageData with Y-up
  // (origin at bottom-left), so the pixel buffer is row-reversed
  // relative to the image. Flip to standard Y-down for descramble,
  // then flip back before putImageData. Pre-copy the buffer so the
  // unscrambled right/bottom margin survives the tile blits.
  const stride = width * 4;
  const srcYup = ctx.getImageData(0, 0, width, height).data;
  const srcStd = new Uint8ClampedArray(srcYup.length);
  for (let y = 0; y < height; y++) {
    srcStd.set(srcYup.subarray(y * stride, (y + 1) * stride), (height - 1 - y) * stride);
  }
  const dstStd = new Uint8ClampedArray(srcStd);

  const rowBytes = tw * 4;
  for (let i = 0; i < lookup.length; i++) {
    const cleanRow = (i / cols) | 0;
    const cleanCol = i % cols;
    const srcIdx = lookup[i]!;
    const srcRow = (srcIdx / cols) | 0;
    const srcCol = srcIdx % cols;
    for (let y = 0; y < th; y++) {
      const srcOff = ((srcRow * th + y) * width + srcCol * tw) * 4;
      const dstOff = ((cleanRow * th + y) * width + cleanCol * tw) * 4;
      dstStd.set(srcStd.subarray(srcOff, srcOff + rowBytes), dstOff);
    }
  }

  const dstYup = new Uint8ClampedArray(dstStd.length);
  for (let y = 0; y < height; y++) {
    dstYup.set(dstStd.subarray(y * stride, (y + 1) * stride), (height - 1 - y) * stride);
  }
  ctx.putImageData(new ImageData(dstYup, width, height), 0, 0);

  return decodeDataUrlToArrayBuffer(canvas.toDataURL(mimeType));
}
